IMPORT JAVA.UTIL.SCANNER;
IMPORT JAVA.UTIL.STRINGTOKENIZER;

PUBLIC CLASS TOKENS {
    PUBLIC STATIC VOID MAIN(STRING[] ARGS) {
        SCANNER SCANNER = NEW SCANNER(SYSTEM.IN);

        // READ THE ENTIRE INPUT LINE
        STRING INPUT = SCANNER.NEXTLINE();
        SCANNER.CLOSE();

        // USE STRINGTOKENIZER TO SPLIT THE INPUT BASED ON SPACES AND PUNCTUATION
        STRINGTOKENIZER TOKENIZER = NEW STRINGTOKENIZER(INPUT, " !,?._'@");

        // PRINT THE NUMBER OF TOKENS
        SYSTEM.OUT.PRINTLN(TOKENIZER.COUNTTOKENS());

        // PRINT EACH TOKEN
        WHILE (TOKENIZER.HASMORETOKENS()) {
            SYSTEM.OUT.PRINTLN(TOKENIZER.NEXTTOKEN());
        }
    }
}


